# Generated by Django 5.0.6 on 2024-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_account_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
            ],
        ),
    ]
