# Generated by Django 5.0.6 on 2024-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('active_date', models.CharField(max_length=255)),
                ('renewal_date', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
